# Generated by Django 3.0.1 on 2020-02-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadat', '0002_webpage_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='item_status',
            field=models.CharField(default='deposited', max_length=264),
        ),
    ]
