# Generated by Django 3.0.1 on 2020-02-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadat', '0003_auto_20200206_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=264, unique=True)),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
            ],
        ),
    ]
